import type { StaticImageData } from "next/image";
import { allSchoolsWithRegion } from "./schoolsData";
import { type Sponsor, sponsorsData } from "./sponsorsData";

export type ArchiveSponsor = {
  name: string;
  logo?: StaticImageData;
};

// Sponsor names per conference year. Names matching an entry in
// sponsorsData render with that logo; the rest render as text via
// LogoTile's name fallback.
const archiveSponsorNames: Record<number, string[]> = {
  2026: ["RBC", "Nokia", "Compulsion Games", "CSE", "Tailed"],
  2025: [
    "RBC",
    "Compulsion Games",
    "Fellow",
    "Ciena",
    "CSE",
    "Gadget",
    "Tailed",
    "Wolfram",
    "Sticker Beaver",
  ],
  2024: ["RBC", "CSE", "Kinaxis", "Accenture", "Fellow"],
  2023: [
    "RBC",
    "Morgan Stanley",
    "Nokia",
    "Deloitte",
    "Accenture",
    "CSE",
    "Sticker Mule",
    "Voiceflow",
  ],
  2022: [
    "Kinaxis",
    "RBC",
    "Unity",
    "Fellow",
    "Geotab",
    "Nokia",
    "Ciena",
    "Diff",
    "iQmetrix",
    "D2L",
  ],
  2021: [
    "RBC",
    "Kinaxis",
    "Morgan Stanley",
    "Genetec",
    "Unity",
    "Amazon",
    "SSENSE",
    "Nokia",
    "Fellow",
    "Balsamiq",
    "Voiceflow",
    "1Password",
    "Egghead",
    "Wonsulting",
    "University of Calgary",
    "Carleton University",
    "University of Toronto",
    "University of Ottawa",
    "University of Waterloo",
  ],
  2020: [
    "Kinaxis",
    "Shopify",
    "RBC",
    "Wish",
    "Morgan Stanley",
    "CSE",
    "CAE",
    "Trip Advisor",
    "Amazon",
    "Fellow",
    "Diff",
    "Knox",
    "1Password",
    "Sticker Mule",
  ],
  2019: [
    "Kinaxis",
    "Morgan Stanley",
    "RBC",
    "Yelp",
    "Wind River",
    "Shopify",
    "IBM",
    "CSE",
    "Qlik",
    "Ubisoft",
    "Fellow",
    "Trip Advisor",
    "AWS",
    "Element AI",
    "NetGovern",
    "Knox",
    "SPIRIA",
    "Diff",
    "Aerotek",
    "Nokia",
    "Sticker Mule",
  ],
  2018: [
    "IBM",
    "RBC",
    "Wind River",
    "CAE",
    "Yelp",
    "Kinaxis",
    "CSE",
    "Morgan Stanley",
    "Ubisoft",
    "Capital One",
    "SAP",
    "Shopify",
    "Sticker Mule",
  ],
  2017: [
    "Kinaxis",
    "Yelp",
    "RBC",
    "CAE",
    "IBM",
    "Ubisoft",
    "CSE",
    "Capital One",
    "Shopify",
    "Morgan Stanley",
    "Wealthsimple",
    "SAP",
    "Wind River",
    "Lightspeed",
    "AppHelp",
    "RealDecoy",
    "BMO",
  ],
  2016: [
    "IBM",
    "CSE",
    "CAE",
    "Yelp",
    "Ubisoft",
    "Morgan Stanley",
    "Shopify",
    "Capital One",
    "RBC",
    "General Motors",
    "Genetec",
    "Trip Advisor",
    "TD",
    "Macadamian",
    "GE",
    "Namecheap",
  ],
  2015: [
    "CAE",
    "Genetec",
    "Microsoft",
    "Yelp",
    "Morgan Stanley",
    "Shopify",
    "Ubisoft",
    "Vision Critical",
    "Mandrill",
    "Google",
    "DigitalOcean",
    "Khan Academy",
    "CSE",
    "Macadamian",
    "Amazon",
  ],
  2014: [
    "CSE",
    "Morgan Stanley",
    "Shopify",
    "Genetec",
    "Microsoft",
    "CAE",
    "Palantir",
    "Google",
    "Nuance",
    "Stripe",
    "Oracle",
    "BNOTIONS",
    "Context.io",
    "Macadamian",
    "360pi",
    "Concordia ENCS",
    "Concordia Institute for Co-operative Education",
    "EA",
    "Velocity",
  ],
  2013: [
    "Palantir",
    "CSE",
    "Amazon",
    "CAE",
    "Concordia ENCS",
    "EMC",
    "Genetec",
    "Google",
    "Microsoft",
    "Morgan Stanley",
    "Nexsan",
    "Radialpoint",
    "SAP",
    "Shopify",
    "Concordia Computer Science",
    "Concordia Institute for Co-operative Education",
    "Macadamian",
    "Technophilic",
    "EA",
    "Benbria",
    "Riot Games",
  ],
  2012: [
    "Riot Games",
    "Dropbox",
    "Adobe",
    "Amazon",
    "Concordia ENCS",
    "Genetec",
    "Microsoft",
    "Morgan Stanley",
    "QNX",
    "SAP",
    "Shopify",
    "Evolving Web",
    "Accedian Networks",
    "Google",
    "Radialpoint",
    "CUTC",
  ],
  2011: [
    "IBM",
    "Vigilant Futures",
    "Direct Energy",
    "Microsoft",
    "Concordia ENCS",
    "SAP",
    "Morgan Stanley",
    "Evertz",
    "Genetec",
    "Evolving Web",
    "TandemLaunch",
    "iWeb Technologies",
    "EA",
    "Ubisoft",
  ],
  2010: [
    "IBM",
    "SAP",
    "Direct Energy",
    "Concordia ENCS",
    "TELUS",
    "Research In Motion",
    "NexJ Systems",
    "Microsoft",
    "Concordia Computer Science",
    "Unipace",
    "Ubisoft",
    "O'Reilly",
    "EA",
  ],
  2009: [
    "Research In Motion",
    "Radialpoint",
    "Extreme Blue",
    "IBM",
    "Concordia ENCS",
    "Microsoft",
    "Evertz",
    "Direct Energy",
    "EA",
    "O'Reilly",
    "Apress",
  ],
  2008: [
    "MANSEF",
    "Direct Energy",
    "SAP",
    "TELUS",
    "Concordia Engineering",
    "Evertz",
    "Autodesk",
    "IBM",
    "Concordia ENCS",
    "Scout Design",
  ],
  2007: [
    "Research In Motion",
    "Business Objects",
    "TELUS",
    "Direct Energy",
    "Infusion Development",
    "EA",
    "Centre Mont-Royal",
    "Holiday Inn",
    "Mega Bloks",
    "Scout Design",
    "O'Reilly",
    "Apress",
  ],
  2006: [
    "Microsoft",
    "EA",
    "Gameloft",
    "Pearson",
    "O'Reilly",
    "Concordia ENCS",
    "McMaster University",
    "Concordia Department of Engineering",
  ],
};

const sponsorsByName = new Map<string, Sponsor>(sponsorsData.map((entry) => [entry.name, entry]));

// Some years (e.g. virtual 2021) were supported by universities; resolve
// their logos from the schools dataset.
const schoolLogosByName = new Map<string, StaticImageData | undefined>(
  allSchoolsWithRegion().map((entry) => [entry.name, entry.logo]),
);

export function getArchiveSponsors(year: number): ArchiveSponsor[] {
  const names = archiveSponsorNames[year] ?? [];
  return names.map((name) => ({
    name,
    logo: sponsorsByName.get(name)?.logo ?? schoolLogosByName.get(name),
  }));
}
