export type ArchiveLink = {
  label: string;
  url: string;
};

export function resolveArchiveUrl(url: string): string {
  if (/^https?:\/\//.test(url) || url.startsWith("/")) {
    return url;
  }
  return `/${url}`;
}

export type ArchiveTalk = {
  title: string;
  presenter: string;
  affiliation?: string;
  links?: ArchiveLink[];
};

export type ArchiveTeamMember = {
  name: string;
  role: string;
};

export type ArchiveYearDetail = {
  year: number;
  theme?: string;
  summary?: string;
  team: ArchiveTeamMember[];
  talks: ArchiveTalk[];
  highlights: ArchiveLink[];
};

export const archiveYearDetails: Record<number, ArchiveYearDetail> = {
  2026: {
    year: 2026,
    summary:
      "The 25th anniversary edition of CUSEC 2026. Held at Hotel Omni Mont-Royal, January 2026. This year, we introduced CUBEAR, CUSEC's mascot. Other big additions to the conference include the Scavenger Hunt, a gamification of the conference experience where delegates can earn points to use towards prizes at the Prize Booth. Other events were introduced such as the CUBEAR Photobooth, Programming Puzzles, and Live Coding.",
    team: [
      { name: "Arfah Huda", role: "Co-Chair" },
      { name: "Jaelyn Wickramarachchi", role: "Co-Chair" },
      { name: "Carson Spriggs-Audet", role: "Director of Logistics" },
      { name: "Franklin Ramirez", role: "Logistics Executive" },
      { name: "McCauley Armishaw", role: "Director of Sponsorships" },
      { name: "Tyrell Haywood", role: "Director of Speakers" },
      { name: "Sirine Tarhouni", role: "Speakers Executive" },
      { name: "Shrey Bhatt", role: "Director of Technology" },
      { name: "Angel Shinh", role: "Director of UI/UX" },
      { name: "Janelle Tam", role: "Director of Events" },
      { name: "Abdel Ait", role: "Events Executive" },
      { name: "Mohammad Akib Hossain", role: "Director of Promotions" },
      { name: "Taryn Beaupre", role: "Graphics Designer" },
      {
        name: "Antonina Kosyakova",
        role: "Head Delegate - John Abbott College",
      },
      { name: "Aran Saseelan", role: "Head Delegate - McMaster University" },
      { name: "Cedric Dimatulac", role: "Head Delegate - University of Ottawa" },
      { name: "Ekamjit Singh", role: "Head Delegate - University of Manitoba" },
      { name: "Jorrell Salazar", role: "Head Delegate - University of Regina" },
      {
        name: "Kelly Nguyen",
        role: "Head Delegate - University of British Columbia",
      },
      {
        name: "Mohammad Affan Shahid",
        role: "Head Delegate - University of Windsor",
      },
      { name: "Paria Jafarian", role: "Head Delegate - Concordia University" },
      { name: "Rumaisa Talukder", role: "Head Delegate - University of Calgary" },
      { name: "Teja Hebbale", role: "Head Delegate - Carleton University" },
      { name: "Tiffany Villatoro", role: "Head Delegate - University of Guelph" },
      { name: "Wasay Aamir", role: "Head Delegate - Ontario Tech University" },
    ],
    talks: [],
    highlights: [],
  },
  2025: {
    year: 2025,
    summary:
      "CUSEC 2025 was held at the Sheraton Hotel in Downtown Montreal in January of 2025 where we welcomed 350+ of Canada's brightest and most ambitious students. This year's Dev's Den had many strong competitors, some of which have gone on to found startups with the projects they pitched at the event.",
    team: [
      { name: "Timothy Klint", role: "Co-Chair" },
      { name: "Kha Pham", role: "Co-Chair" },
      { name: "Jaelyn Wickramarachchi", role: "Director of Logistics" },
      { name: "Michael Xie", role: "Logistics Team" },
      { name: "Angeleeca Jocson", role: "Director of Sponsorship" },
      { name: "Arfah Huda", role: "Sponsorship Team" },
      {
        name: "Carson Spriggs-Audet",
        role: "Head Delegate & Sponsorship Team - Concordia University",
      },
      { name: "Tara Denaud Joseph", role: "Director of Speakers" },
      { name: "Janelle Tam", role: "Speakers Team" },
      { name: "Tyrell Haywood", role: "Director of Technology" },
      { name: "Taryn Beaupre", role: "Director of Promotions & Tech UI/UX Design" },
      { name: "Hana Louiza Moussaoui", role: "Promotions Team & Design" },
      { name: "Shrey Bhatt", role: "Head Delegate - Seneca Polytechnic" },
      { name: "Muhammad Rafiuzzaman", role: "Head Delegate - University of Calgary" },
      { name: "Franklin Ramirez", role: "Head Delegate - University of Waterloo" },
      { name: "Daniel Arulpragasam", role: "Head Delegate - Carleton University" },
      { name: "Joshua Lebert", role: "Head Delegate - University of Windsor" },
      { name: "Fay Lee", role: "Head Delegate - University of Ottawa" },
      { name: "Pooja Patel", role: "Head Delegate - University of Regina" },
    ],
    talks: [],
    highlights: [],
  },
  2024: {
    year: 2024,
    summary:
      "CUSEC 2024 was held at the Sheraton Hotel in Downtown Montreal in January of 2024. Speakers from leading game studios, big tech, AI startups, academia and more!",
    team: [
      { name: "Jordon Hong", role: "Co-Chair" },
      { name: "Denys Popov", role: "Co-Chair" },
      { name: "Kha Pham", role: "Director of Logistics" },
      { name: "Abdul-Hakim Skaik", role: "Director of Logistics" },
      { name: "Jaelyn Wick", role: "Director of Sponsorship" },
      { name: "Mumtahin Farabi", role: "Director of Technology" },
      { name: "Bavneet Sandhu", role: "Technology Team" },
      { name: "Angeleeca Jocson", role: "Director of Speakers" },
      { name: "Smriti Hari", role: "Speakers Team" },
      {
        name: "Timothy J. Klint",
        role: "Director of Events & Head Delegate - Montreal",
      },
      { name: "Anjali Patel", role: "Director of Promotions" },
      { name: "Ethan Tang", role: "Promotions Team" },
      { name: "Arfah Huda", role: "Head Delegate - University of Windsor" },
      { name: "Hoang Minh Phan", role: "Head Delegate - University of Manitoba" },
      { name: "Maheen Raza", role: "Head Delegate - University of Calgary" },
      {
        name: "Ayesha Izzati",
        role: "Head Delegate - University of British Columbia",
      },
      { name: "Aran Saseelan", role: "Head Delegate - McMaster University" },
      { name: "Shashwat Murawala", role: "Head Delegate - University of Waterloo" },
      { name: "Sirine Tarhouni", role: "Head Delegate - McGill University" },
      { name: "Hanine Tydrini", role: "Head Delegate - Concordia University" },
      { name: "Tara Denaud Joseph", role: "Head Delegate - University of Ottawa" },
      { name: "Julie Wechsler", role: "Head Delegate - Carleton University" },
    ],
    talks: [],
    highlights: [],
  },
  2023: {
    year: 2023,
    summary:
      "CUSEC 2023 was held at Hotel Bonaventure in Downtown Montreal in January of 2023. We welcomed talented students from across the country to hear from leaders and innovators in tech, from Grady Booch (creator of UML) to Shelli Brunswick (COO of the Space Foundation).",
    team: [
      { name: "Charmaine Yung", role: "Co-Chair" },
      { name: "David Chen", role: "Co-Chair" },
      { name: "Denys Popov", role: "Director of Logistics" },
      { name: "Sarah Veloso", role: "Logistics Executive" },
      { name: "Kha Pham", role: "Director of Sponsorships" },
      { name: "Camila Martínez Ovando", role: "Director of Speakers" },
      { name: "Lyka M. Sal-long", role: "Speakers Executive" },
      { name: "Abdul-Hakim Skaik", role: "Director of Technology" },
      { name: "Danielle D'Souza", role: "Technology Executive" },
      { name: "Melissa Lin", role: "Technology Executive" },
      { name: "Jaelyn Wickramarachchi", role: "Director of Events" },
      { name: "Jordon Hong", role: "Director of Promotions" },
      { name: "Marianne Jane Angga", role: "Promotions Executive" },
      { name: "Anjali Patel", role: "Head Delegate - Carleton University" },
      { name: "Ara Nicole Santos", role: "Head Delegate - University of Manitoba" },
      { name: "Kevin Liang", role: "Head Delegate - McGill University" },
      {
        name: "Kisenge Mbaga",
        role: "Head Delegate - University of New Brunswick",
      },
      { name: "Mohammad Zafar", role: "Head Delegate - University of Regina" },
      { name: "Yashpreet Singh", role: "Head Delegate - University of Calgary" },
      { name: "Yasin Elmi", role: "Head Delegate - University of Ottawa" },
    ],
    talks: [],
    highlights: [],
  },
  2022: {
    year: 2022,
    summary:
      "CUSEC 2022 was held virtually in January 2022. Speakers ranged from Michael Seibel, CEO and Partner at Y Combinator, Cindy Alvarez, Director of Customer Research at GitHub, Engineers and Leaders from various big tech and AI startups.",
    team: [
      { name: "HaoHao Du", role: "Chair" },
      { name: "Isham Singh Behl", role: "Chair" },
      { name: "Turja Chowdhury", role: "Director of Logistics" },
      { name: "Nick Duan", role: "Logistics Team" },
      { name: "Kenny Nguyen", role: "Director of Sponsorship" },
      { name: "Denys Popov", role: "Sponsorship Team" },
      { name: "Ish Khattar", role: "Sponsorship Team" },
      { name: "David Chen", role: "Director of Speakers" },
      { name: "Aisorya Bhandari", role: "Speakers Team" },
      { name: "Omar Flores", role: "Director of Technology" },
      { name: "Charmaine Yung", role: "Technology Team" },
      { name: "Emily Jiawei Chen", role: "Director of Events" },
      { name: "Ann Trinh", role: "Director of Promotions" },
      { name: "Andrea Abellera", role: "Promotions Team" },
      { name: "Ali Aftab Muhammad", role: "Head Delegate - University of Ottawa" },
      { name: "Kunal Rajpal", role: "Head Delegate - University of Manitoba" },
      { name: "Aaditya Chopra", role: "Head Delegate - Carleton University" },
      { name: "Ines Rosito", role: "Head Delegate - University of Calgary" },
      { name: "Safiya Mufti", role: "Head Delegate - University of Waterloo" },
      { name: "Mohanna Shahrad", role: "Head Delegate - McGill University" },
    ],
    talks: [],
    highlights: [],
  },
  2021: {
    year: 2021,
    theme: "Virtual Conference",
    summary:
      "CUSEC 2021 was held virtually in January 2021, welcoming 650+ passionate students to hear from industry leaders at AWS, MongoDB, box, RBC, Tech Inquiry, Apple, Microsoft, and many more.",
    team: [
      { name: "Ellen Li", role: "Co-Chair" },
      { name: "Nathan Tozer", role: "Co-Chair" },
      { name: "Isham Behl", role: "Director of Logistics" },
      { name: "Tanner Dunn", role: "Logistics Team" },
      { name: "Tommy Deng", role: "Director of Technology & Design" },
      { name: "Gordon Pham-Nguyen", role: "Technology and Design Team" },
      { name: "Tae Kim", role: "Director of Events" },
      { name: "Aisorya Bhandari", role: "Co-Director of Sponsorship" },
      { name: "Kisenge Mbaga", role: "Co-Director of Sponsorship" },
      { name: "Vivian Diec", role: "Director of Promotions" },
      { name: "HaoHao Du", role: "Head Delegate - Carleton University" },
      { name: "Esther Guerrier", role: "Head Delegate - Polytechnique Montréal" },
      { name: "Edison Guillermo", role: "Head Delegate - University of Manitoba" },
      { name: "Karl Zhu", role: "Head Delegate - University of Waterloo" },
      { name: "Trang Vu", role: "Head Delegate - University of New Brunswick" },
      { name: "Wendy Yang", role: "Head Delegate - University of Calgary" },
      { name: "Hervé Egla", role: "Head Delegate - University of Ottawa" },
      { name: "Matthieu Chan Chee", role: "Head Delegate - University of Toronto" },
    ],
    talks: [],
    highlights: [],
  },
  2020: {
    year: 2020,
    summary:
      "CUSEC 2020 was held in Montreal January 2020. Welcoming 450+ Canadian students to hear from renown speakers such as Mayuko Inoue, Puneet Mulchandani, Kristina Balaam, Jackie Chi Kit Cheung, Maude Lemaire, Kate Arthur, and many, many more!",
    team: [
      { name: "Laura Wheatley", role: "Head Delegate - Universities in Montreal" },
      { name: "Michael Walz", role: "Head Delegate - University of New Brunswick" },
      { name: "Ellen Li", role: "Head Delegate - University of Ottawa" },
      { name: "Hamna Nimra Manzoor", role: "Head Delegate - Carleton University" },
      { name: "Liam Walsh", role: "Head Delegate - Queen's University" },
      { name: "Ida Liu", role: "Head Delegate - University of Toronto" },
      { name: "Hrayr Mkrtchyan", role: "Head Delegate - University of Guelph" },
      { name: "Isham Singh Behl", role: "Head Delegate - University of Manitoba" },
      { name: "Ayush Kapur", role: "Head Delegate - University of Waterloo" },
    ],
    talks: [],
    highlights: [],
  },
  2019: {
    year: 2019,
    summary:
      "CUSEC 2019 was held in Montreal, Quebec in January 2019. Over 450+ passionate learners and builders from across Canada came together to learn from great minds and leaders like Gelu Ticala, Matt Lee, Amanda Cox, Jin Guo, Matthieu Courbariaux, Maxwell Elendt, Kim Noel, Olivier Bilodeau, and many more.",
    team: [
      { name: "Vinith Suriyakumar", role: "Co-Chair" },
      { name: "Sébastien Roy", role: "Co-Chair" },
      { name: "Seara Chen", role: "Speakers Team" },
      { name: "Laura Wheatley", role: "Director of Speakers" },
      { name: "Ife Agiri", role: "Director of Promotions" },
      { name: "Anushka Paliwal", role: "Director of Sponsorship" },
      { name: "Zach Hauser", role: "Director of Logistics" },
      { name: "Dema Abu Adas", role: "Director of Events" },
      { name: "Bernie", role: "Director of Design" },
      { name: "Samira El-Rayyes", role: "Director of Finance" },
      { name: "Aanika Rahman", role: "Logistics Team" },
      { name: "Raiyan Quaium", role: "Head Delegate - Carleton University" },
      { name: "Mivia Li", role: "Head Delegate - University of Waterloo" },
      { name: "Sawaiba Sial", role: "Head Delegate - University of Guelph" },
      { name: "Niyousha Saeidi", role: "Head Delegate - Queen's University" },
      { name: "Vivian Diec", role: "Head Delegate - University of Ottawa" },
      { name: "Olivier Gamache", role: "Head Delegate - Université Laval" },
      { name: "Julia Athayde", role: "Head Delegate - University of Manitoba" },
      { name: "Mila Roisin", role: "Head Delegate - Concordia University" },
      { name: "Nathan Tozer", role: "Head Delegate - University of New Brunswick" },
    ],
    talks: [],
    highlights: [],
  },
  2018: {
    year: 2018,
    summary:
      "CUSEC 2018 was held in Montreal in January 2018. 500+ students from top universities in Canada grouped together at Hotel Bonaventure to hear from speakers such as Eva Galperin, Steve Klabnik, David Lyon, Vadim Makarov, Robert Fratila, Christian Joudrey, Nicolas Le Roux, and so many more talented pioneers.",
    team: [
      { name: "Gracey Hlywa Maytan", role: "Co-Chair" },
      { name: "Kenny Hong", role: "Co-Chair" },
      { name: "Paul Lee", role: "Director of Sponsorship" },
      { name: "Zach Hauser", role: "Sponsorship Team" },
      { name: "Aniqah Mair", role: "Director of Speakers" },
      { name: "James Talarico", role: "Speakers Team" },
      { name: "Vinith Suriyakumar", role: "Director of Events" },
      { name: "Jonathan Gratton", role: "Director of Technology" },
      { name: "Sébastien Roy", role: "Director of Logistics" },
      { name: "Laura Wheatley", role: "Logistics Team" },
      { name: "Abby Leung", role: "Director of Promotions" },
      { name: "Samira El-Rayyes", role: "Director of Finance" },
      { name: "Elisa Kazan", role: "Head Delegate - Carleton University" },
      { name: "Bailey Shirtliff", role: "Head Delegate - University of Manitoba" },
      { name: "Pouya Lajevardi", role: "Head Delegate - University of Toronto" },
      { name: "Jacob Smith", role: "Head Delegate - University of New Brunswick" },
      { name: "Dema Abu Adas", role: "Head Delegate - University of Guelph" },
      { name: "Bernard Cloutier", role: "Head Delegate - Concordia University" },
      { name: "Abhishek Dhakla", role: "Head Delegate - University of Waterloo" },
      { name: "Belkheir Anis", role: "Head Delegate - Polytechnique" },
      { name: "Sebastian Hoefert", role: "Head Delegate - Queen's University" },
      { name: "Anushka Paliwal", role: "Head Delegate - University of Ottawa" },
    ],
    talks: [],
    highlights: [],
  },
  2017: {
    year: 2017,
    summary:
      "CUSEC 2017 was held in Montreal in January 2017. Welcoming 550+ passionate students from across Canada along with talented and renown speakers such as David Nolen, Lynn Root, Tracy Osborn, Emil Stolarsky, Florencia Herra-Vega, Jamie Wong, Lei Lopez, Peter Sobot, and so many more.",
    team: [
      { name: "Kim Noel", role: "CUSEC 2017 Chair" },
      { name: "Aniqah Mair", role: "Director of Speakers" },
      { name: "Dhiren Audich", role: "Director of Design" },
      { name: "Gracey Hlywa-Maytan", role: "Director of Logistics" },
      { name: "James Talarico", role: "Logistics Team" },
      { name: "Jonathan Gratton", role: "Director of Events" },
      { name: "Kenny Hong", role: "Director of Sponsorship" },
      { name: "Sébastien Roy", role: "Director of A/V" },
      { name: "Alan Bridgeman", role: "Head Delegate - University of Manitoba" },
      { name: "Alessandro Power", role: "Head Delegate - Concordia University" },
      { name: "Angelo Austria", role: "Head Delegate - University of Toronto" },
      { name: "Chirag Gada", role: "Head Delegate - University of Waterloo" },
      { name: "Ivona Sikiric", role: "Head Delegate - York University" },
      { name: "Nabil Sakran", role: "Head Delegate - McMaster University" },
      { name: "Paul Lee", role: "Head Delegate - University of Ottawa" },
      { name: "Vinith Suriyakumar", role: "Head Delegate - Queen's University" },
    ],
    talks: [],
    highlights: [],
  },
  2016: {
    year: 2016,
    summary:
      "CUSEC 2016 was held in Montreal in January 2016. Over 500+ of the best students from across Canada came together to learn from those leading the industry and pushing new technologies forward. Speakers such as Kate Heddleston, Carina C. Zona, Michael Bernstein, Julia Evans, and many more.",
    team: [
      { name: "Dominic Charley-Roy", role: "Co-Chair" },
      { name: "Alexander Coco", role: "Co-Chair" },
      { name: "Yann Landry", role: "Director of A/V" },
      { name: "Kimberly Tran", role: "Co-Director of Logistics" },
      { name: "Kathy Luo", role: "Co-Director of Logistics" },
      { name: "Miguel Ocampo-Gooding", role: "Design Team" },
      { name: "Stephanie Zeidan", role: "Director of Events" },
      { name: "David Kua", role: "Director of Speakers" },
      { name: "Kim Noel", role: "Director of Sponsorship" },
      { name: "Laura Alkhoury", role: "Promotions Team" },
      { name: "Edward Ntiri", role: "Sponsorship Team" },
      { name: "Jeff Tuxworth", role: "Head Delegate - York University" },
      { name: "Aniqah Mair", role: "Head Delegate - Queen's University" },
      { name: "Gracey Hlywa Maytan", role: "Head Delegate - Concordia University" },
      { name: "Julian Horvat", role: "Head Delegate - University of Guelph" },
      { name: "Jonathan Gratton", role: "Head Delegate - University of Ottawa" },
      { name: "Kenny Hong", role: "Head Delegate - University of Manitoba" },
      { name: "Sean Ghazazani", role: "Head Delegate - Carleton University" },
    ],
    talks: [],
    highlights: [],
  },
  2015: {
    year: 2015,
    summary:
      "CUSEC 2015 was held in Montreal, January 2015 bringing together eager students and industry leaders such as Aaron Patterson, Julie Pagano, Camille Fournier, Sandi Metz, Bruce Schneier, David Wolever, Christopher Stumm, Hicham Ratnani, and so many more.",
    team: [
      { name: "Samira El-Rayyes", role: "Co-Chair" },
      { name: "Santiago Gil", role: "Co-Chair" },
      { name: "Patrick Nguyen", role: "Director of Logistics" },
      { name: "Kimberly Noel", role: "Logistics Team" },
      { name: "Alexander Coco", role: "Director of Sponsorship" },
      { name: "Xenia Tay", role: "Sponsorship Team" },
      { name: "Aiman Khan", role: "Director of A/V" },
      { name: "Dominic Charley-Roy", role: "Director of Speakers" },
      { name: "David Kua", role: "Speakers Team" },
      { name: "Kat Drobnjakovic", role: "Webmaster" },
      { name: "Zichen Jiang", role: "AV Team" },
      { name: "Miguel Ocampo-Gooding", role: "Design Team" },
      { name: "Rohan Likhite", role: "Design Team" },
      { name: "Stephanie Zeidan", role: "Promotion Team" },
      { name: "Tahia Khan", role: "Head Delegate - University of Toronto" },
      { name: "Farwa Naqi", role: "Head Delegate - University of Waterloo" },
      { name: "James Pang", role: "Head Delegate - Queen's University" },
      { name: "Julian Horvat", role: "Head Delegate - University of Guelph" },
      { name: "Keiko Climaco", role: "Head Delegate - University of Ottawa" },
      { name: "Maude Lemarie", role: "Head Delegate - McGill University" },
      { name: "Peter Hoang", role: "Head Delegate - McMaster University" },
      {
        name: "TingLi Lucia Lorigiano",
        role: "Head Delegate - Concordia University",
      },
      { name: "Ursula Sarracini", role: "Head Delegate - York University" },
    ],
    talks: [],
    highlights: [],
  },
  2014: {
    year: 2014,
    summary:
      "CUSEC 2014 was held in Montreal in January 2014, welcoming hundreds of the best students from across Canada to hear from renown leaders and recognizeable faces such as Bruce Eckel, Gary Bernhardt, Kelsey Gilmore-Innis, Michelle Zatlyn, Zach Holman, Bruno Morency, Ian Chan, and so, so many more.",
    team: [
      { name: "Alex Selesse", role: "Co-Chair" },
      { name: "Matthew Leavitt", role: "Co-Chair" },
      { name: "Alex Coco", role: "Co-Director of Logistics" },
      { name: "Michael Lakhia", role: "Co-Director of Logistics" },
      { name: "Xenia Tay", role: "Webmaster" },
      { name: "Samira El-Rayyes", role: "Director of Sponsorship" },
      { name: "Bowen Xu", role: "Sponsorship Team" },
      { name: "Dominic Charley-Roy", role: "Director of Speakers" },
      { name: "Santiago Gil", role: "Director of Promotions" },
      { name: "Mohammed Chamma", role: "Director of AV" },
      { name: "Danielle Pham", role: "AV Team" },
      { name: "Patrick Nguyen", role: "Head Delegate - Concordia University" },
      { name: "Kruti Bagde", role: "Head Delegate - Carleton University" },
      { name: "Sami Jaber", role: "Head Delegate - McGill University" },
      { name: "Saif Myageri", role: "Head Delegate - McMaster University" },
      { name: "Aimal Khan", role: "Head Delegate - McMaster University" },
      { name: "Jamie Bannerman", role: "Head Delegate - Queen's University" },
      { name: "Julian Horvat", role: "Head Delegate - University of Guelph" },
      { name: "Stephanie Zeidan", role: "Head Delegate - University of Ottawa" },
      { name: "David Kua", role: "Head Delegate - Univesity of Toronto" },
      { name: "Alykhan Kanji", role: "Head Delegate - University of Waterloo" },
      { name: "Vaughan Hills", role: "Head Delegate - Wilfrid Laurier University" },
      { name: "Nataly Sheinin", role: "Head Delegate - York University" },
      { name: "Miguel Ocampo-Gooding", role: "Head Delegate - York University" },
    ],
    talks: [],
    highlights: [],
  },
  2013: {
    year: 2013,
    summary:
      "CUSEC 2013 was held in Montreal, January 2013. Hundreds of the most passionate students and learners came together to hear from the best of the best, notable speakers such as Ben Fry, Maciej Ceglowski, Benjamin Black, Ian Goldberg, Michelle Levesque, Jessica McKellar, Gail Carmichael, and countless more.",
    team: [
      { name: "Alexandra Phillips", role: "Co-Chair" },
      { name: "Carla Morawicz", role: "Co-Chair" },
      { name: "Mitch Smolash", role: "Director of Logistics" },
      { name: "Alexander Coco", role: "Webmaster" },
      { name: "Alex Selesse", role: "Co-Director of Sponsorship" },
      { name: "Razvan Lada-Moldovan", role: "Co-Director of Sponsorship" },
      { name: "Samira El-Rayyes", role: "Director of Promotions" },
      { name: "Tavish Armstrong", role: "Director of AV" },
      { name: "Mohammed Chamma", role: "AV Team" },
      { name: "Antoine Grondin", role: "Head Delegate - University of Ottawa" },
      { name: "Bowen Xu", role: "Head Delegate - University of Waterloo" },
      { name: "Caradec Bisesar", role: "Head Delegate - University of Toronto" },
      { name: "Daniel Ricci", role: "Head Delegate - Concordia University" },
      { name: "Danielle Fudger", role: "Head Delegate - University of Guelph" },
      { name: "Kruti Bagde", role: "Head Delegate - Carleton University" },
      { name: "Santiago Gil", role: "Head Delegate - University of Waterloo" },
    ],
    talks: [],
    highlights: [],
  },
  2012: {
    year: 2012,
    theme: "Turing Complete",
    summary:
      "CUSEC 2012, January 2012, Montreal. Simple enough. The biggest CUSEC to date bringing speakers from across the globe. Some notable names include Alexis Ohanian, Jeremy Ashkenas, Gayle L. McDowell, Greg Kroah-Hartman, Bret Victor, Andrew Rothbart, and so many more.",
    team: [
      { name: "Vijeta Patel", role: "Chair" },
      { name: "Thomas Hibbert", role: "Director of Finance" },
      { name: "Matthew Leavitt", role: "Director of Speakers" },
      { name: "Corey Clayton", role: "Speakers Team" },
      { name: "Phill Mendonca-Vieira", role: "Speakers Advisor" },
      { name: "Carla Morawicz", role: "Director of Sponsorship" },
      { name: "Mitch Smolash", role: "Director of Logistics" },
      { name: "Tavish Armstrong", role: "Logistics Team" },
      { name: "Alexandra Phillips", role: "Director of Promotions" },
      { name: "Lucas Bokos", role: "Promotions Team" },
      { name: "Eric Chan", role: "Web Team" },
      { name: "Alex Craig", role: "Head Delegate - Carleton University" },
      {
        name: "Kyle Sama and Daniel Ricci",
        role: "Head Delegate - Concordia University",
      },
      {
        name: "Marc-Etienne M.Léveillé",
        role: "Head Delegate - École de technologie supérieure",
      },
      { name: "Chad Chabot", role: "Head Delegate - University of Guelph" },
      { name: "Alex Selesse", role: "Head Delegate - McGill University" },
      { name: "Matt Nelson", role: "Head Delegate - McMaster University" },
      { name: "Maryleen Mompoint", role: "Head Delegate - Université de Moncton" },
      { name: "Andréa Bourdeau", role: "Head Delegate - University of Ottawa" },
      { name: "Chris Cooper", role: "Head Delegate - Queen's University" },
      {
        name: "Johnathan Hok",
        role: "Head Delegate - University of Toronto at Scarborough",
      },
      {
        name: "Alex Krassikov",
        role: "Head Delegate - University of Toronto at St. George",
      },
      { name: "Dan Mathers", role: "Head Delegate - Trent University" },
      { name: "Kevin Veloso", role: "Head Delegate - University of Waterloo" },
    ],
    talks: [],
    highlights: [{ label: "Pictures", url: "http://flickr.com/search/?q=cusec2012&m=tags" }],
  },
  2011: {
    year: 2011,
    theme: "Hello World",
    summary:
      "CUSEC 2011 was held in January 2011 in Downtown Montreal. We welcomed hundreds of students ready to learn from renown & influential speakers such as Yehuda Katz, Michael Lopp (Rands), Drew Conway, Julie Steele, Ben Fry, Mike Shaver, Eric Diep, Sha Xin Wei, and many more.",
    team: [
      { name: "Thomas Hibbert", role: "Co-Chair" },
      { name: "Sven James", role: "Co-Chair" },
      { name: "Abdullah Salim", role: "Director of Finance" },
      { name: "Phill Mendonca-Vieira", role: "Director of Speakers" },
      { name: "Alex Daskalov", role: "Speakers Team" },
      { name: "Matthew Gallant", role: "Speakers Team" },
      { name: "Mathieu Dumais-Savard", role: "Sponsorship Team" },
      { name: "Yagnik Khanna", role: "Sponsorship Team" },
      { name: "Vijeta Patel", role: "Director of Logistics" },
      { name: "Stephen Krujelskis", role: "Director of Promotions" },
      { name: "Alexandra Phillips", role: "Promotions Team" },
      { name: "Jonathon Marcogliese", role: "Director of Web" },
      { name: "Nicole Waldrum", role: "Head Delegate - Carleton University" },
      {
        name: "Eric Chan and Corey Clayton",
        role: "Head Delegate - Concordia University",
      },
      {
        name: "Marc-Etienne M.Léveillé",
        role: "Head Delegate - École de technologie supérieure",
      },
      { name: "Alex Daskalov", role: "Head Delegate - McGill University" },
      { name: "Marc Lafratta", role: "Head Delegate - McMaster University" },
      { name: "Maryleen Mompoint", role: "Head Delegate - Université de Moncton" },
      { name: "Dan Godfrey", role: "Head Delegate - University of Ottawa" },
      { name: "Mike Zalewski", role: "Head Delegate - Queen's University" },
      { name: "Jules Delisle", role: "Head Delegate - Université de Sherbrooke" },
      {
        name: "George Ju",
        role: "Head Delegate - University of Toronto at St. George",
      },
      { name: "Dan Mathers", role: "Head Delegate - Trent University" },
      {
        name: "Roshane Silva and Saumaya Sharma",
        role: "Head Delegate - University of Waterloo",
      },
    ],
    talks: [],
    highlights: [
      { label: "Proceedings", url: "archives/2011/proceedings2011.pdf" },
      { label: "Pictures", url: "http://flickr.com/search/?q=cusec2011&m=tags" },
    ],
  },
  2010: {
    year: 2010,
    theme: "GOTO 10",
    summary: "Information is being compiled.",
    team: [
      { name: "Andrew Louis", role: "Co-Chair" },
      { name: "Juan Musleh", role: "Co-Chair" },
      { name: "Abdullah Salim", role: "Director of Finance" },
      { name: "Phill Mendonca-Vieira", role: "Speaker Team" },
      { name: "William Hua", role: "Speaker Team" },
      { name: "Sven James", role: "Sponsorship Team" },
      { name: "Ahmed Ben Messaoud", role: "Sponsorship Team" },
      { name: "Thomas Hibbert", role: "Logistics Team" },
      { name: "Clara Choi", role: "Logistics Team" },
      { name: "Todd Ritchie", role: "Logistics Team" },
      { name: "Denis Zgonjanin", role: "Head Delegate - Carleton University" },
      {
        name: "Matthew Gallant and Vijeta Patel",
        role: "Head Delegate - Concordia University",
      },
      {
        name: "Marc-Etienne M.Léveillé",
        role: "Head Delegate - École de technologie supérieure",
      },
      { name: "Chantal Bisson", role: "Head Delegate - Université Laval" },
      { name: "Alex Daskalov", role: "Head Delegate - McGill University" },
      { name: "Alex Aylwin", role: "Head Delegate - McMaster University" },
      { name: "Dan Godfrey", role: "Head Delegate - University of Ottawa" },
      {
        name: "Lori Lee",
        role: "Head Delegate - University of Toronto at St. George",
      },
      {
        name: "Dan Malakieh and Kerryck Jones",
        role: "Head Delegate - University of Waterloo",
      },
      {
        name: "Adam Van Ymeren",
        role: "Head Delegate - University of Western Ontario",
      },
    ],
    talks: [],
    highlights: [
      { label: "Proceedings", url: "archives/2010/proceedings2010.pdf" },
      { label: "Pictures", url: "http://flickr.com/search/?q=cusec2010&m=tags" },
    ],
  },
  2009: {
    year: 2009,
    theme: "Software (R)evolutions",
    summary: "Information is being compiled.",
    team: [
      { name: "Linda Wang", role: "Co-Chair" },
      { name: "Eitan 'Skrud' Levi", role: "Co-Chair" },
      { name: "Abdullah Salim", role: "Director of Finance" },
      { name: "Andrew Louis", role: "Director of Presentations" },
      { name: "William Hua", role: "Director of Academic Presentations" },
      { name: "Juan Musleh", role: "Director of Sponsorship" },
      { name: "Claudiu Scotnotis", role: "Director of Logistics" },
      { name: "Aran Donohue", role: "Director of Promotions" },
      { name: "Kyle Sama", role: "Director of Events" },
      { name: "Guillaume Theoret", role: "Webmaster" },
      { name: "Rebecca Cohen Palacios", role: "Website Designer" },
      { name: "Denis Zgonjanin", role: "Head Delegate - Carleton University" },
      {
        name: "Matthew Gallant and Vijeta Patel",
        role: "Head Delegate - Concordia University",
      },
      {
        name: "Gabriel Grise",
        role: "Head Delegate - École de technologie supérieure",
      },
      {
        name: "Julien Gascon-Samson",
        role: "Head Delegate - École Polytechnique de Montréal",
      },
      { name: "Chantal Bisson", role: "Head Delegate - Université Laval" },
      { name: "Thomas Hibbert", role: "Head Delegate - McGill University" },
      { name: "Asadullah Baig", role: "Head Delegate - McMaster University" },
      { name: "Ahmed Ben Messaoud", role: "Head Delegate - University of Ottawa" },
      { name: "Jenn Clarke", role: "Head Delegate - Queen's University" },
      { name: "Robyn Scholes", role: "Head Delegate - Royal Military College" },
      {
        name: "Ebenezer 'Eben' Hailemariam",
        role: "Head Delegate - University of Toronto at St. George",
      },
      {
        name: "Abe Tsang",
        role: "Head Delegate - University of Toronto at Scarborough",
      },
      {
        name: "Sze Man Clara Choi and Tyler Szabo",
        role: "Head Delegate - University of Waterloo",
      },
      {
        name: "Adam Van Ymeren",
        role: "Head Delegate - University of Western Ontario",
      },
    ],
    talks: [],
    highlights: [
      { label: "Proceedings", url: "archives/2009/proceedings2009.pdf" },
      { label: "Pictures", url: "http://flickr.com/search/?q=cusec2009&m=tags" },
    ],
  },
  2008: {
    year: 2008,
    theme: "Making it Fun",
    summary: "Information is being compiled.",
    team: [
      { name: "Abdullah Salim", role: "Co-Chair" },
      { name: "Hugo Levasseur", role: "Co-Chair" },
      { name: "Neeraj Mathrani", role: "Director of Finance" },
      {
        name: "Edward Ocampo-Gooding",
        role: "Director of Presentations and Keynotes",
      },
      { name: "Aran Donohue", role: "Director of Academic Presentations" },
      { name: "Igor Foox", role: "Director of Corporate Presentations" },
      { name: "Louis-Philippe Huberdeau", role: "Account Manager" },
      { name: "Rami Ayyad", role: "Account Manager" },
      { name: "Linda Wang", role: "Co-Director of Logistics" },
      { name: "Michelle Chua", role: "Co-Director of Logistics" },
      { name: "Juan Musleh", role: "Director of University Relations" },
      { name: "Eitan Levi", role: "Director of Promotions" },
      { name: "Julie Hache", role: "Director of Events" },
      { name: "Richard Shih", role: "Website Director" },
      { name: "Abdo Mazloum", role: "Head Delegate - Bishop's University" },
      {
        name: "Denis Zgonjanin and Gerald Orban",
        role: "Head Delegate - Carleton University",
      },
      { name: "Claudiu Scotnotis", role: "Head Delegate - Concordia University" },
      {
        name: "Julien Godin-Viau",
        role: "Head Delegate - École de technologie supérieure",
      },
      {
        name: "Colin Martel",
        role: "Head Delegate - École Polytechnique de Montréal",
      },
      { name: "Steve Fortier", role: "Head Delegate - Université Laval" },
      { name: "Ashton Anderson", role: "Head Delegate - McGill University" },
      { name: "Juan Musleh", role: "Head Delegate - McMaster University" },
      {
        name: "Jacques-Andre Doucet",
        role: "Head Delegate - Université de Moncton",
      },
      { name: "Alex McNamara", role: "Head Delegate - University of Ottawa" },
      {
        name: "Ngouana Sugewe G. Francis",
        role: "Head Delegate - Université du Québec en Outaouais",
      },
      { name: "Tim Ginn", role: "Head Delegate - Queen's University" },
      { name: "Robyn Scholes", role: "Head Delegate - Royal Military College" },
      { name: "Andrew Louis", role: "Head Delegate - University of Toronto" },
      {
        name: "Marieke Talens and Yubin Kim",
        role: "Head Delegate - University of Waterloo",
      },
      {
        name: "Mila Milojevic and Victoria Odeyemi",
        role: "Head Delegate - University of Western Ontario",
      },
    ],
    talks: [
      {
        title: "Hard Problems in Network Computing",
        presenter: "Tim Bray",
        affiliation: "Director of Web Technologies, Sun Microsystems",
        links: [{ label: "Video", url: "http://vimeo.com/2333320" }],
      },
      {
        title: "We Didn't Start the Fire",
        presenter: "Sylvain Carle",
        affiliation: "Founder and CTO, Praized Media",
        links: [
          { label: "Video", url: "http://vimeo.com/2396555" },
          { label: "PDF", url: "archives/2008/sylvain_carle.pdf" },
        ],
      },
      {
        title: "Performance Analysis and Tuning Techniques witin Enterprise Applications",
        presenter: "Chris Collition",
        affiliation: "Manager, Enterprise Architecture, TELUS",
        links: [{ label: "Video", url: "http://vimeo.com/2461682" }],
      },
      {
        title: "Hacking the Noosphere",
        presenter: "Jon Udell",
        affiliation: "Technical Evangelist, Microsoft",
        links: [{ label: "Video", url: "http://vimeo.com/2563536" }],
      },
      {
        title: "Living with Concurrency",
        presenter: "Dr. Peter Grogono",
        affiliation: "Professor, Concordia University",
        links: [
          { label: "Video", url: "http://vimeo.com/2598809" },
          { label: "PDF", url: "archives/2008/peter_grogono.pdf" },
        ],
      },
      {
        title: "When Theory Matters",
        presenter: "Dr. Jeffrey Ullman",
        affiliation: "Professor Emeritus, Stanford University",
        links: [
          { label: "Video", url: "http://vimeo.com/2658924" },
          { label: "PDF", url: "archives/2008/jeffrey_ullman.pdf" },
        ],
      },
      {
        title: "The ACL is Dead",
        presenter: "Zed Shaw",
        affiliation: "Developer, Mongrel Web Server",
        links: [{ label: "Video", url: "http://vimeo.com/2723800" }],
      },
      {
        title: "Is Writing More Important Than Programming?",
        presenter: "Jeff Atwood",
        affiliation: "Blogger, codinghorror.com",
        links: [
          { label: "Video", url: "http://vimeo.com/2796392" },
          { label: "PDF", url: "archives/2008/jeff_atwood.pdf" },
        ],
      },
      {
        title: "Zed Shaw on Factor",
        presenter: "Zed Shaw",
        affiliation: "Developer, Mongrel Web Server",
      },
      {
        title: "Technology, Creativity, Stress and Hockey",
        presenter: "Bruce Miner",
        affiliation: "Direct Energy",
      },
      {
        title: "Building your software start up and having fun doing it!",
        presenter: "Leila Boujnane and Paul Bloore",
        affiliation: "Co-Founders, Idee Inc.",
      },
      {
        title: "Music and Games: How Fun Applications Stimulate Core Technologies",
        presenter: "Dr. Jeremy Cooperstock",
        affiliation: "Professor, McGill University",
        links: [{ label: "Video", url: "http://vimeo.com/cusec" }],
      },
      {
        title: "Keeping It Fun: Hacking on Open Source After Graduation",
        presenter: "Jeff Bailey",
        affiliation: "Google",
      },
      {
        title: "Creating fast, maintainable and secure parsers with Ragel",
        presenter: "Adrian Thurston",
        affiliation: "Ph.D Student, Queen's University",
      },
    ],
    highlights: [
      { label: "Proceedings", url: "archives/2008/proceedings2008.pdf" },
      { label: "Pictures", url: "http://flickr.com/search/?q=cusec2008&m=tags" },
    ],
  },
  2007: {
    year: 2007,
    theme: "Designing for the Future",
    summary: "Information is being compiled.",
    team: [
      { name: "Neeraj Mathrani", role: "Chair" },
      { name: "John Sloboda", role: "Director of Finance" },
      { name: "Hugo Levasseur", role: "Director of Presentations" },
      { name: "Oralndo Marquez", role: "Director of Keynotes" },
      { name: "Walid Koleilat", role: "Director of Academic Presentations" },
      { name: "Michelle Chua", role: "Director of Corporate Presentations" },
      { name: "George Gao", role: "Co-Director of Sponsorship" },
      { name: "Linda Wang", role: "Co-Director of Sponsorship" },
      { name: "Rami Ayyad", role: "Co-Director of Sponsorship" },
      { name: "Linda Wang", role: "Co-Director of Logistics" },
      { name: "Karen Widish", role: "Director of Promotions" },
      { name: "Kalu Kalu", role: "Director of Interactive Events" },
      {
        name: "Richard Shih",
        role: "Art, Website and Registration Website Director",
      },
      { name: "Mitra Nami", role: "Volunteer" },
      {
        name: "Edward Ocampo-Gooding",
        role: "Head Delegate - Bishop's University",
      },
      { name: "Karen Widish", role: "Head Delegate - Carleton University" },
      { name: "Hugo Levasseur", role: "Head Delegate - Concordia University" },
      {
        name: "Louis-Philippe Huberdeau",
        role: "Head Delegate - École de technologie supérieure",
      },
      {
        name: "Benoit Lapensée",
        role: "Head Delegate - École Polytechnique de Montréal",
      },
      {
        name: "Georges-Etienne Legendre",
        role: "Head Delegate - Université Laval",
      },
      { name: "Kevin Wong", role: "Head Delegate - McGill University" },
      { name: "Abdullah Salim", role: "Head Delegate - McMaster University" },
      { name: "Julie Hache", role: "Head Delegate - Université de Moncton" },
      { name: "Louis Lemaire", role: "Head Delegate - Royal Military College" },
      { name: "Igor Foox", role: "Head Delegate - University of Toronto" },
      { name: "Julian Spillane", role: "Head Delegate - University of Waterloo" },
      {
        name: "Victoria Odeyemi",
        role: "Head Delegate - University of Western Ontario",
      },
    ],
    talks: [],
    highlights: [
      { label: "Proceedings", url: "archives/2007/proceedings2007.pdf" },
      { label: "Pictures", url: "http://flickr.com/search/?q=cusec2007&m=tags" },
    ],
  },
  2006: {
    year: 2006,
    theme: "Engineering Useful Software",
    summary: "Information is being compiled.",
    team: [
      { name: "John Kopanas", role: "Chair" },
      { name: "Mark Pavlidis", role: "Director of Finance" },
      {
        name: "Ahmed Kamel",
        role: "Director of Keynote, Corporate and Tutorial Presentations",
      },
      {
        name: "Ashraf Gaffar",
        role: "Director of Academic and Paper Presentations",
      },
      { name: "Neeraj Mathrani", role: "Director of Corporate Sponsorship" },
      { name: "Nadia Chaouch", role: "Director of Logistics and Website" },
      { name: "Michel Parisien", role: "Director of Promotions" },
    ],
    talks: [
      {
        title: "Creating Passionate Users",
        presenter: "Kathy Sierra",
        affiliation: "Author and Publisher of O'Reilly's Head First series of books",
      },
      {
        title: "Fight The Traffic",
        presenter: "Chad Fowler",
        affiliation: 'Author of "My Job Went To India" and "Rails Recipes"',
        links: [{ label: "PDF", url: "archives/2006/fowler.pdf" }],
      },
      {
        title: "Modular Concurrency",
        presenter: "Peter Grogono",
        affiliation:
          "Professor and Associate Chair, Department of Computer Science and Software Engineering, Concordia University",
        links: [{ label: "PDF", url: "archives/2006/grogono.pdf" }],
      },
      {
        title: "Rails is Boring and Ruby is a Toy",
        presenter: "Chad Fowler",
        affiliation: 'Author of "My Job Went To India" and "Rails Recipes"',
      },
      {
        title: "Software Testing as a Social Science",
        presenter: "Cem Kaner",
        affiliation: "Professor of Software Engineering, Florida Institute of Technology",
        links: [{ label: "PDF", url: "archives/2006/kaner.pdf" }],
      },
      {
        title: "Agile - Helping You Deliver More Useful Software",
        presenter: "Francois Beauregard",
        affiliation: "VP Research and Development, Pyxis Technologies",
        links: [{ label: "PDF", url: "archives/2006/beauregard.pdf" }],
      },
      {
        title: "Software Start Up",
        presenter: "Laurent Seiter",
        links: [
          { label: "PowerPoint", url: "archives/2006/seiter.ppt" },
          { label: "PDF", url: "archives/2006/seiter.pdf" },
        ],
      },
      {
        title: "The Challenge of Testing In A Creative Environment",
        presenter: "Karine Roy",
        affiliation: "SQA Manager, Autodesk Media and Entertainment",
        links: [{ label: "PDF", url: "archives/2006/roy.pdf" }],
      },
      {
        title: "Eclipse Performance",
        presenter: "Chris Laffra",
        affiliation: "Rational Performance Engineering Team, IBM",
        links: [
          { label: "PDF", url: "archives/2006/laffra.pdf" },
          { label: "PPT", url: "archives/2006/laffra.ppt" },
        ],
      },
      {
        title: "Considering AJAX",
        presenter: "Chris Laffra",
        affiliation: "Rational Performance Engineering Team, IBM",
        links: [{ label: "Web Slides", url: "http://www.eclipsefaq.org/chris/ajax/" }],
      },
    ],
    highlights: [
      { label: "Website", url: "http://cusec2006.soen.info" },
      { label: "Proceedings", url: "archives/2006/proceedings2006.pdf" },
      {
        label: "Pictures",
        url: "http://www.flickr.com/photos/kopanas/sets/72057594057116818/",
      },
    ],
  },
  2005: {
    year: 2005,
    theme: "Thinking Outside the Cubicle",
    summary: "Information is being compiled.",
    team: [
      { name: "Chris Donaldson", role: "Director of Physical Things" },
      { name: "Karen Widish", role: "Director of Other Physical Things" },
      { name: "Michael Smith", role: "Director of Audible Things" },
      { name: "Matt Gawlik", role: "Director of Common Sense" },
      { name: "Andrew Dunbar", role: "Director of Safety and Fun" },
      { name: "Sherwin Sim", role: "Director of Seating" },
      { name: "Wataru Watanabe", role: "Graphic Design" },
    ],
    talks: [
      {
        title: "Can the Means Justify the End? - Saving Programs from Programming",
        presenter: "Branislav Selic",
        affiliation: "Distinguished Engineer, IBM Rational Software Canada",
        links: [
          { label: "PowerPoint", url: "archives/2005/selic.ppt" },
          { label: "PDF", url: "archives/2005/selic.pdf" },
        ],
      },
      {
        title: "Software Development as a Cooperative Game of Invention and Communication",
        presenter: "Alistair Cockburn",
        affiliation: "President, Humans and Technology",
        links: [
          {
            label: "Methodologies as Swimsuits",
            url: "archives/2005/MethodologiesAsSwimsuits.ppt",
          },
        ],
      },
      {
        title: "Engineering High Quality Software Applications",
        presenter: "Dr. Alan Wassyng",
        affiliation: "Associate Professor, McMaster University",
        links: [
          { label: "PowerPoint", url: "archives/2005/wassyng.ppt" },
          { label: "PDF", url: "archives/2005/wassyng.pdf" },
        ],
      },
      {
        title: "Is Emotion Relevant to Requirements Engineering",
        presenter: "Dr. Daniel M. Berry",
        affiliation: "Professor, University of Waterloo",
        links: [{ label: "PDF", url: "archives/2005/berry.pdf" }],
      },
      {
        title: "Multidisciplinary Participatory Design Environment",
        presenter: "Jonathan Benn",
        affiliation: "B.Eng., Graduate Student, Concordia University",
        links: [
          { label: "PowerPoint", url: "archives/2005/benn.ppt" },
          { label: "PDF", url: "archives/2005/benn.pdf" },
        ],
      },
      {
        title: "MDA: What is in it for Patterns",
        presenter: "Ashraf Gaffar",
        affiliation: "Graduate Student, Concordia University",
        links: [{ label: "PDF", url: "archives/2005/gaffar.pdf" }],
      },
      {
        title: "Using CVS to Manage Student Assignments",
        presenter: "Dr. Greg Wilson, Adjunct Professor and Karen Reid, Lecturer",
        affiliation: "University of Toronto",
        links: [
          { label: "PowerPoint", url: "archives/2005/wilsonReid.ppt" },
          { label: "PDF", url: "archives/2005/wilsonReid.pdf" },
        ],
      },
      {
        title: "Subversion",
        presenter: "Chris Ness",
        affiliation: "Undergraduate Student, McMaster University",
        links: [{ label: "PDF", url: "archives/2005/ness.pdf" }],
      },
      {
        title: "A Real-World Development Life Cycle",
        presenter: "Dr. Greg Wilson",
        affiliation: "Adjunct Professor, University of Toronto",
        links: [
          { label: "PowerPoint", url: "archives/2005/wilson.ppt" },
          { label: "PDF", url: "archives/2005/wilson.pdf" },
        ],
      },
      {
        title: "How to develop software? Don't - most of it is out there, adapt it.",
        presenter: "Jerzy Prekurat",
        links: [{ label: "PowerPoint", url: "archives/2005/prekurat.ppt" }],
      },
    ],
    highlights: [
      {
        label: "Pictures",
        url: "http://www.flickr.com/photos/kopanas/sets/988102/",
      },
    ],
  },
  2004: {
    year: 2004,
    theme: "Ensuring the Quality",
    summary: "Information is being compiled.",
    team: [
      { name: "Joël Migneault", role: "Chair" },
      { name: "Gregory Sagget-Rudd", role: "VP Presentations" },
      { name: "Alexandre Lampron", role: "VP Communication & Finance" },
      { name: "Madhumita Banerjee", role: "VP Finance" },
      { name: "Vincent Dionne", role: "VP Logistics" },
      { name: "Ahmed Kamel", role: "VP Technology & Presentations" },
      {
        name: "Nadia Chaouch",
        role: "Logistic & Presentations & Executive Assistant",
      },
      { name: "Leon McKernan-Milon", role: "Finance" },
      { name: "Pier-Luc St-Onge", role: "Communication" },
      { name: "Dominic Lagarde", role: "Communication" },
      { name: "Maxime Clerk-Lamalice", role: "Communication" },
      { name: "Audrey Girouard", role: "Logistics" },
      { name: "Sandrine Tiné", role: "Logistics" },
      { name: "Fanny Waffo", role: "Logistics" },
      { name: "Ndeye-Syra Ba", role: "Logistics" },
      { name: "Ka Lun Sze", role: "Competition" },
      { name: "Frédéric Rioux", role: "Central Committee" },
    ],
    talks: [],
    highlights: [
      {
        label: "Pictures",
        url: "http://www.flickr.com/photos/kopanas/sets/1041664/",
      },
    ],
  },
  2003: {
    year: 2003,
    theme: "Adapting The Process",
    summary: "Information is being compiled.",
    team: [
      { name: "John Kopanas", role: "Chair" },
      { name: "Frédéric Rioux", role: "Director of Presentations" },
      { name: "Chae Dickie-Clark", role: "Director of Finance" },
      { name: "Jacinthe Gagnon", role: "Director of Operations" },
      { name: "Thanh Vinh Tang", role: "Director of Industry Relations" },
      { name: "Yann McCready", role: "Director of Inter-University Promotions" },
      { name: "Jia-Wei Zhang", role: "Director of Inter-University Promotions" },
      { name: "Mark Abbyad", role: "Director of Activities and Kangaroos" },
      { name: "Francois-Michel Brière", role: "Director of Exhibitions" },
      {
        name: "Gaspard Petit",
        role: "Director of Software Engineering Competition",
      },
      {
        name: "Marc-André Laverdière",
        role: "Director of Software Engineering Competition",
      },
    ],
    talks: [
      {
        title: "Les Principes Fondamentaux du Génie Logiciel",
        presenter: "Normand Séguin",
        affiliation: "Professor, Computer Science Department, UQAM",
        links: [
          { label: "PowerPoint", url: "archives/2003/seguin.ppt" },
          { label: "PDF", url: "archives/2003/seguin.pdf" },
        ],
      },
      {
        title: "Accreditation of Software Engineering Programs by the CSAC",
        presenter: "Guy Tremblay",
        affiliation: "UQAM & Member of CSAC",
        links: [{ label: "PDF", url: "archives/2003/tremblay.pdf" }],
      },
      {
        title: "Atelier: Les Inspections Logicielles",
        presenter: "Sylvie Trudel",
        affiliation: "CRIM",
        links: [
          { label: "PowerPoint", url: "archives/2003/trudel.ppt" },
          { label: "PDF", url: "archives/2003/trudel.pdf" },
        ],
      },
      {
        title: "Testing Interactions Among Software Components",
        presenter: "Alan Williams",
        affiliation: "School of Information Technology and Engineering, University of Ottawa",
        links: [
          { label: "PowerPoint", url: "archives/2003/williams.ppt" },
          { label: "PDF", url: "archives/2003/williams.pdf" },
        ],
      },
    ],
    highlights: [],
  },
};

export function getArchiveYearDetail(year: number): ArchiveYearDetail | undefined {
  return archiveYearDetails[year];
}
