export const historicSpeakersData: Record<number, string[]> = {
  2026: [
    "Fatima Taj",
    "Prijan Keth",
    "Gail Carmichael",
    "Zach Holman",
    "Marcelo Ardilles",
    "Cameron Alexander",
    "TJ Klint",
    "Laurence Liang",
    "Alex Velazquez",
    "Vicky Desjardins",
    "Rida Mehdi",
    "Ananya Nair",
    "Alexa Stroll",
  ],
  2025: [
    "Greg Wilson",
    "Lyn Chen",
    "Edwin Sarmiento",
    "Fatima Taj",
    "Nivy Kani",
    "Rue Sriharsha",
    "Shan Wu",
    "Matthew MacRae-Bovell",
    "Bilal Ahktar",
    "Gaia Noseworthy",
    "Tony Xu",
    "Florent Giraud",
    "Mukund Mauji",
    "Jocelyn Murphy",
    "Maya Lekhi",
    "Victor Li",
    "Rabab Azeem",
    "Sophy Sun",
  ],
  2024: [
    "Antonio Gutiérrez",
    "Gazi Jarin",
    "Fatima Taj",
    "Prashanthi Ramesh",
    "Georges-Antoine Assi",
    "Eleanor Rumsey",
    "Samuel Cormier-Iijima",
    "Michael Chan",
    "Devon Knight",
    "Aaditya Chopra",
    "Claudiu Scotnotis",
    "Victor Li",
    "Matthew MacRae-Bovell",
    "Rue Sriharsha",
  ],
  2023: [
    "Alex Karp",
    "Auguste Rame",
    "Dylan Steen",
    "Eddie Hinkle",
    "Falah Shazib",
    "Fatima Taj",
    "Grady Booch",
    "Kiefer Co",
    "Matthew MacRae-Bovell",
    "Matthew Pan",
    "Nathan Laundry",
    "Nikki Babaii Kochekseraii",
    "Raymond Chung",
    "Sanaa Syed",
    "Selvi Arora",
    "Shelli Brunswick",
    "Shubh Bhalla",
    "Tae Kim",
  ],
  2022: [
    "Michael Seibel",
    "Cindy Alvarez",
    "Jimena Almendares",
    "Peter Moore",
    "Fatima Taj",
    "Forest Anderson",
    "Iris Wen",
    "Jimoh Ovbiagele",
    "Yulia Eskin",
    "Amar Jasarbasic",
    "Alex Cui",
    "Alexa Liaskovski",
    "David Hew-wing",
    "Dawn Chandler",
    "Erin Gallagher",
    "Jenny Pan",
    "Raman Lally",
    "Raymond Chung",
  ],
  2021: [
    "Shelli Brunswick",
    "Jack Poulson",
    "Andra Keay",
    "William Hurley",
    "Stephanie A. Higa",
    "Patrick Colucci",
    "Jerry Lee",
    "Adrienne Tacke",
    "Emmanuel Straschnov",
    'Qianyun "Aria" Chang',
    "Alex Catus",
    "Ahmed Yasser",
    "Anita Popescu",
    "Eric Chau",
    "Megan Doherty",
  ],
  2020: [
    "Puneet Mulchandani",
    "Kate Gregory",
    "Toria Gibbs",
    "Mayuko Inoue",
    "Phillip Williams",
    "Erica Engle",
    "Kate Arthur",
    "Maude Lemaire",
    "Forest Anderson",
    "Megan Doherty",
    "Nicolas Cuillery",
    "Kristina Balaam",
    "Jackie Chi Kit Cheung",
    "Angelo Pengue",
    "André Gauthier",
    "Abdou Sarr",
    "Princejeet Singh Sandhu",
  ],
  2019: [
    "Gelu Ticala",
    "Matt Lee",
    "Sarah Kraynick",
    "Eyra Abraham",
    "Yasmin Alameddine",
    "Amanda Cox",
    "Jin Guo",
    "Tobias Coetzee",
    "Matthieu Courbariaux",
    "Maxwell Elendt",
    "Kim Noel",
    "Pierre-Luc Maheu",
    "Nicolas Cuillery",
    "Kathy Giori",
    "Mallar Chakravarty",
    "Olivier Bilodeau",
    "Andrew Louis",
  ],
  2018: [
    "Eva Galperin",
    "Steve Klabnik",
    "David Lyon",
    "Vadim Makarov",
    "Lori Olson",
    "Karen Sandler",
    "Jacob Cook",
    "Jim Duey",
    "Robert Fratila",
    "Mike Hoye",
    "Christian Joudrey",
    "Nicolas Le Roux",
    "Kim Moir",
    "Arshia Mufti",
    "Jake Pittis",
    "Mahtab Sabet",
    "Julian Squires",
    "Kaitlyn Yong",
  ],
  2017: [
    "Amar Shah",
    "David Nolen",
    "Liz Abinante",
    "Lynn Root",
    "Sarah Mei",
    "Tracy Osborn",
    "Berkley Staite",
    "Emil Stolarsky",
    "Florencia Herra-Vega",
    "Huma Zafar",
    "Jamie Wong",
    "Jessica Thompson",
    "Kamal Marhubi",
    "Lei Lopez",
    "Peter Sobot",
    "Riley J. Shaw",
    "Sarah Anne Friend",
    "Prof. Sharief Oteafy",
  ],
  2016: [
    "Carina C. Zona",
    "Kate Heddleston",
    "Michael Bernstein",
    "Jeff Hodges",
    "Julia Evans",
    "Alex Selesse",
    "Dann Toliver",
    "Julie Hache",
    "Laurie Hendren",
    "Prakash Panangaden",
    "Simon Eskildsen",
    "Josh Matthews",
    "Robin Grosset",
    "Lucille Hua",
    "Fiona Condon",
    "Daniel Lanthier",
    "Nathan Powell",
  ],
  2015: [
    "Aaron Patterson",
    "Julie Pagano",
    "Camille Fournier",
    "Sandi Metz",
    "Dr. Jeff Chastine",
    "Bruce Schneier",
    "David Wolever",
    "Christopher Stumm",
    "Elida Arrizza",
    "Dr. Helge Seetzen",
    "Dr. Joelle Pineau",
    "Rami Sayar",
    "Jeff Preshing",
    "Greg Ward",
    "Fred Hatfull",
    "Jenny Zhang",
    "Monica Dinculescu",
    "Hicham Ratnani",
  ],
  2014: [
    "Bruce Eckel",
    "Gary Bernhardt",
    "Kelsey Gilmore-Innis",
    "Michelle Zatlyn",
    "Zach Holman",
    "Don Olmstead",
    "Avi Bryant",
    "Bruno Morency",
    "Dr. Derek Ruths",
    "Ian Chan",
    "Josh Matthews",
    "Julia Evans",
    "Maria Smirnoff",
    "Matt Helm",
    "Nabil Al-Azem",
    "Nadim Kobeissi",
    "Nahim Nasser",
    "Tony Hooper",
  ],
  2013: [
    "Ben Fry",
    "Maciej Ceglowski",
    "Benjamin Black",
    "Ian Goldberg",
    "Michelle Levesque",
    "Jessica McKellar",
    "Gail Carmichael",
    "Jonathan Brun",
    "Richard Gate",
    "Nick Edouard",
    "Andrew Louis",
    "Rami Sayar",
    "Dr. Paul Cisek",
    "Dr. Sabine Bergler",
    "Michael Wojcikiewicz",
    "Doug Tetzner",
    "Daniel Robinson",
    "Susan Ibach",
  ],
  2012: [
    "Alexis Ohanian",
    "Jeremy Ashkenas",
    "Gayle L. McDowell",
    "Greg Kroah-Hartman",
    "Bret Victor",
    "Andrew Rothbart",
    "Manveer Heir",
    "Susan Ibach",
    "Frederic Lalonde",
    "Alex Daskalov",
    "Harry Brundage",
    "Vic Keenan",
    "Rian Hunter",
    "Charles Desjardins",
    "Mathieu Chevalier",
    "Dr. Brian Cantwell Smith",
    "Atefeh Farzindar Ph. D",
    "Dr. Marcelo M. Wanderley",
  ],
  2011: [
    "Yehuda Katz",
    "Michael Lopp (Rands)",
    "Drew Conway",
    "Julie Steele",
    "Ben Fry",
    "Mike Shaver",
    "Guy Barette",
    "Eric Diep",
    "Edward Ocampo-Gooding",
    "Daniel Beauchamp",
    "Moataz Abdellateef",
    "Mark Jorgensen",
    "Marc-Antoine Ruel",
    "Martin Drapeau",
    "Paul Kry",
    "Derek Ruths",
    "Sha Xin Wei",
  ],
  2010: [
    "Reginald Braithwaite",
    "Douglas Crockford",
    "Jacqui Maher",
    "Matthew Knox",
    "Thomas Ptacek",
    "Greg Wilson",
    "Pete Forde",
    "Michael Jones",
    "Rob Tyrie",
    "David Turek",
    "Dan Berry",
    "Constantinos Constantinides",
    "Doug Down",
    "Mohammed Eid",
    "Nizar Sakr",
  ],
  2009: [
    "Leah Culver",
    "Francis Hwang",
    "Avi Bryant",
    "Dan Ingalls",
    "Richard Stallman",
    "Giles Bowkett",
    "Jonathan Edwards",
    "Jörg Kienzle",
    "Steve Easterbrook",
    "Caitlin Kelleher",
    "Jói Sigurðsson",
    "Joey deVilla",
    "Vince Silvestri",
    "Marty Algire",
    "Colin Smillie",
    "Mark Pavlidis",
    "James Golick",
  ],
  2008: [
    "Jeff Atwood",
    "Jeff Ullman",
    "Zed Shaw",
    "Tim Bray",
    "Marcel Molina",
    "Jon Udell",
    "Marsha Chechik",
    "Jeremy Cooperstock",
    "Ettore Merlo",
    "Adrian Thurston",
    "Sylvain Carle",
    "Julian Spillane",
  ],
  2007: [
    "Dave Thomas",
    "Pete McBreen",
    "Ralph E. Johnson",
    "James R. Cordy",
    "Dr. Venkat Subramanian",
    "Dr. Lee McIntyre",
    "Nikolas Landry",
    "Michelle Levesque",
    "Geoff Guenther",
    "Greg Brill",
    "Thomas Wieberneit",
    "Dr. Mourad Debbabi",
    "Dr. Jeremy Cooperstock",
    "Dr. Gail C. Murphy",
    "Dr. Timothy C. Lethbridge",
    "Dr. Michael Godfrey",
    "Nicolas Dube",
  ],
  2006: [
    "Peter Grogono",
    "David Heinemeier Hansson",
    "Kathy Sierra",
    "Chad Fowler",
    "Connie Heitmeyer",
    "Karine Roy",
    "Patrick Ng",
    "Aditya Thakur",
    "Gang(George) Zhu",
    "Robert Sabourin",
    "Chris Laffra",
    "Louenas Hamdi",
    "Alex Hyder",
    "Nancy Acemian",
    "Dr. Peter Forbrig",
    "Dr. Cem Kaner",
    "Dr. Ahmed Seffah",
    "Laurent Seiter",
    "Orlando Marquez",
  ],
  2005: [
    "Tony Bailetti",
    "Alistair Cockburn",
    "J. B. (Joe) Rainsberger",
    "Bran Selic",
    "Alan Wassyng",
    "Jonathan Benn",
    "Ashraf Gaffar",
    "Greg Wilson",
    "Karen Reid",
    "Daniel Berry",
    "Robert Biddle",
    "Pankaj Kamthan",
    "Daniel Sinnig",
    "Lawrence Liu",
    "Jerzy Prekurat",
    "Chris Ness",
    "Dave Rooney",
  ],
  2004: [
    "Pierre N. Robillard, Ph.D.",
    "Lionel C. Briand, Ph.D.",
    "David Lorge Parnas, Ph.D.",
    "Joel Spolsky",
    "Krzysztof Czarnecki, Ph.D.",
    "Frédéric Rioux",
    "Sebastien Cherry",
    "François Lemieux",
    "Xuyen On",
    "Sylvain Béland",
    "Tuomas Klemola",
  ],
  2003: ["Kent Beck", "Dr. Peter Grogono", "Hal Helms", "Dr. Philippe Kruchten", "Craig Larman"],
};
