import { z } from "zod";

const sponsorLinksSchema = z.record(z.string().min(1), z.url());

export const sponsorLinks = sponsorLinksSchema.parse({
  "1Password": "https://1password.com/",
  Accenture: "https://www.accenture.com/",
  Adobe: "https://www.adobe.com/",
  Aerotek: "https://www.aerotek.com/",
  Amazon: "https://www.amazon.com/",
  AppDirect: "https://www.appdirect.com/",
  Apress: "https://www.apress.com/",
  Autodesk: "https://www.autodesk.com/",
  AWS: "https://aws.amazon.com/",
  Balsamiq: "https://balsamiq.com/",
  Benbria: "https://www.benbria.com/",
  BMO: "https://www.bmo.com/",
  CAE: "https://www.cae.com/",
  "Capital One": "https://www.capitalone.com/",
  Ciena: "https://www.ciena.com/",
  Cisco: "https://www.cisco.com/",
  "Compulsion Games": "https://www.compulsiongames.com/",
  CSE: "https://www.cse-cst.gc.ca/",
  CUTC: "https://cutc.ca/",
  D2L: "https://www.d2l.com/",
  Deloitte: "https://www.deloitte.com/",
  Diff: "https://www.diffagency.com/",
  DigitalOcean: "https://www.digitalocean.com/",
  "Direct Energy": "https://www.directenergy.com/",
  Dropbox: "https://www.dropbox.com/",
  EA: "https://www.ea.com/",
  Egghead: "https://egghead.io/",
  Emids: "https://www.emids.com/",
  Evertz: "https://evertz.com/",
  "Evolving Web": "https://evolvingweb.com/",
  Fellow: "https://fellow.app/",
  Gadget: "https://gadget.dev/",
  Gameloft: "https://www.gameloft.com/",
  GE: "https://www.ge.com/",
  Genetec: "https://www.genetec.com/",
  Geotab: "https://www.geotab.com/",
  "General Motors": "https://www.gm.com/",
  Google: "https://www.google.com/",
  IBM: "https://www.ibm.com/",
  iQmetrix: "https://www.iqmetrix.com/",
  "Khan Academy": "https://www.khanacademy.org/",
  Kinaxis: "https://www.kinaxis.com/",
  Knox: "https://www.linkedin.com/company/knox/",
  Leaseweb: "https://www.leaseweb.com/",
  Lightspeed: "https://www.lightspeedhq.com/",
  "Mega Bloks": "https://www.megabrands.com/",
  Microsoft: "https://www.microsoft.com/",
  "Microsoft Azure": "https://azure.microsoft.com/",
  "Morgan Stanley": "https://www.morganstanley.com/",
  Namecheap: "https://www.namecheap.com/",
  "NexJ Systems": "https://www.linkedin.com/company/nexj-systems/",
  Nexsan: "https://www.nexsan.com/",
  Nokia: "https://www.nokia.com/",
  Numerator: "https://www.numerator.com/",
  "O'Reilly": "https://www.oreilly.com/",
  Oracle: "https://www.oracle.com/",
  Palantir: "https://www.palantir.com/",
  Qlik: "https://www.qlik.com/",
  QNX: "https://blackberry.qnx.com/",
  RBC: "https://www.rbc.com/",
  RealDecoy: "https://www.realdecoy.com/",
  "Research In Motion": "https://www.blackberry.com/",
  "Riot Games": "https://www.riotgames.com/",
  SAP: "https://www.sap.com/",
  ServiceNow: "https://www.servicenow.com/",
  Shopify: "https://www.shopify.com/",
  SPIRIA: "https://www.spiria.com/",
  SSENSE: "https://www.ssense.com/",
  "Sticker Beaver": "https://stickerbeaver.ca/",
  "Sticker Mule": "https://www.stickermule.com/",
  Stripe: "https://stripe.com/",
  Tailed: "https://www.linkedin.com/company/tailed/",
  TandemLaunch: "https://www.tandemlaunch.com/",
  TD: "https://www.td.com/",
  TELUS: "https://www.telus.com/",
  "Trip Advisor": "https://www.tripadvisor.com/",
  Ubisoft: "https://www.ubisoft.com/",
  Unity: "https://unity.com/",
  Velocity: "https://velocityincubator.com/",
  Voiceflow: "https://www.voiceflow.com/",
  Wealthsimple: "https://www.wealthsimple.com/",
  Wish: "https://www.wish.com/",
  Wolfram: "https://www.wolfram.com/",
  Wonsulting: "https://www.wonsulting.com/",
  Yelp: "https://www.yelp.com/",
});

export function getSponsorLink(sponsorName: string) {
  return (
    sponsorLinks[sponsorName] ??
    `https://www.linkedin.com/search/results/companies/?keywords=${encodeURIComponent(sponsorName)}`
  );
}
